version: "3.7"

volumes:
  data:

services:

  database:
    build:
      dockerfile: docker/mysql/Dockerfile
      context: .
    volumes:
      - data:/var/lib/mysql
    restart: always
    container_name: mysql
    env_file: .env

  webserver:
    build:
      dockerfile: docker/wordpress/Dockerfile
      context: .
    depends_on:
      - database
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - ./config/wordpress/:/var/www/
      - ./config/apache2/:/etc/apache2/sites-available/
    environment:
      - WORDPRESS_DB_HOST=database:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    ports:
      - "80:80"
